# Generated by Django 2.0.2 on 2018-03-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=200)),
                ('eventDate', models.CharField(max_length=50)),
                ('eventTime', models.CharField(max_length=50)),
                ('eventLocation', models.CharField(max_length=200)),
                ('eventDescription', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
