# Generated by Django 2.0 on 2018-04-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ama', '0007_home_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['eventDate', 'eventTime']},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={'ordering': ['memberLastName', 'memberFirstName']},
        ),
        migrations.AddField(
            model_name='members',
            name='memberEmail',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='memberID',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
